/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddRouteImport } from './routes/add'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as HomeRouteImport } from './routes/home'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AuthDeniedRouteImport } from './routes/auth.denied'
import { Route as AuthStartRouteImport } from './routes/auth.start'
import { Route as DriveSetupRouteImport } from './routes/drive.setup'
import { Route as PurchaseIdRouteImport } from './routes/purchase.$id'
import { Route as AuthDriveCallbackRouteImport } from './routes/auth.drive.callback'
import { Route as AuthDriveStartRouteImport } from './routes/auth.drive.start'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDeniedRoute = AuthDeniedRouteImport.update({
  id: '/auth/denied',
  path: '/auth/denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStartRoute = AuthStartRouteImport.update({
  id: '/auth/start',
  path: '/auth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveSetupRoute = DriveSetupRouteImport.update({
  id: '/drive/setup',
  path: '/drive/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseIdRoute = PurchaseIdRouteImport.update({
  id: '/purchase/$id',
  path: '/purchase/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDriveCallbackRoute = AuthDriveCallbackRouteImport.update({
  id: '/auth/drive/callback',
  path: '/auth/drive/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDriveStartRoute = AuthDriveStartRouteImport.update({
  id: '/auth/drive/start',
  path: '/auth/drive/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/archive': typeof ArchiveRoute
  '/home': typeof HomeRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/auth/denied': typeof AuthDeniedRoute
  '/auth/start': typeof AuthStartRoute
  '/drive/setup': typeof DriveSetupRoute
  '/purchase/$id': typeof PurchaseIdRoute
  '/auth/drive/callback': typeof AuthDriveCallbackRoute
  '/auth/drive/start': typeof AuthDriveStartRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/archive': typeof ArchiveRoute
  '/home': typeof HomeRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/auth/denied': typeof AuthDeniedRoute
  '/auth/start': typeof AuthStartRoute
  '/drive/setup': typeof DriveSetupRoute
  '/purchase/$id': typeof PurchaseIdRoute
  '/auth/drive/callback': typeof AuthDriveCallbackRoute
  '/auth/drive/start': typeof AuthDriveStartRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/archive': typeof ArchiveRoute
  '/home': typeof HomeRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/auth/denied': typeof AuthDeniedRoute
  '/auth/start': typeof AuthStartRoute
  '/drive/setup': typeof DriveSetupRoute
  '/purchase/$id': typeof PurchaseIdRoute
  '/auth/drive/callback': typeof AuthDriveCallbackRoute
  '/auth/drive/start': typeof AuthDriveStartRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/archive'
    | '/home'
    | '/search'
    | '/settings'
    | '/auth/denied'
    | '/auth/start'
    | '/drive/setup'
    | '/purchase/$id'
    | '/auth/drive/callback'
    | '/auth/drive/start'
    | '/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/archive'
    | '/home'
    | '/search'
    | '/settings'
    | '/auth/denied'
    | '/auth/start'
    | '/drive/setup'
    | '/purchase/$id'
    | '/auth/drive/callback'
    | '/auth/drive/start'
    | '/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/archive'
    | '/home'
    | '/search'
    | '/settings'
    | '/auth/denied'
    | '/auth/start'
    | '/drive/setup'
    | '/purchase/$id'
    | '/auth/drive/callback'
    | '/auth/drive/start'
    | '/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  ArchiveRoute: typeof ArchiveRoute
  HomeRoute: typeof HomeRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  AuthDeniedRoute: typeof AuthDeniedRoute
  AuthStartRoute: typeof AuthStartRoute
  DriveSetupRoute: typeof DriveSetupRoute
  PurchaseIdRoute: typeof PurchaseIdRoute
  AuthDriveCallbackRoute: typeof AuthDriveCallbackRoute
  AuthDriveStartRoute: typeof AuthDriveStartRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/denied': {
      id: '/auth/denied'
      path: '/auth/denied'
      fullPath: '/auth/denied'
      preLoaderRoute: typeof AuthDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/start': {
      id: '/auth/start'
      path: '/auth/start'
      fullPath: '/auth/start'
      preLoaderRoute: typeof AuthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive/setup': {
      id: '/drive/setup'
      path: '/drive/setup'
      fullPath: '/drive/setup'
      preLoaderRoute: typeof DriveSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/$id': {
      id: '/purchase/$id'
      path: '/purchase/$id'
      fullPath: '/purchase/$id'
      preLoaderRoute: typeof PurchaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/drive/callback': {
      id: '/auth/drive/callback'
      path: '/auth/drive/callback'
      fullPath: '/auth/drive/callback'
      preLoaderRoute: typeof AuthDriveCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/drive/start': {
      id: '/auth/drive/start'
      path: '/auth/drive/start'
      fullPath: '/auth/drive/start'
      preLoaderRoute: typeof AuthDriveStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  ArchiveRoute: ArchiveRoute,
  HomeRoute: HomeRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  AuthDeniedRoute: AuthDeniedRoute,
  AuthStartRoute: AuthStartRoute,
  DriveSetupRoute: DriveSetupRoute,
  PurchaseIdRoute: PurchaseIdRoute,
  AuthDriveCallbackRoute: AuthDriveCallbackRoute,
  AuthDriveStartRoute: AuthDriveStartRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
